---
- fail: msg="admin list is empty"
  when: jupyterhub_admins|length == 0

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory

- name: copy Dockerfile for jupyterhub
  template: src=Dockerfile.jupyterhub.j2 dest=/srv/jupyterhub/Dockerfile

- name: create the jupyterhub configuration file
  template: src=jupyterhub_config.py.j2 dest=/srv/jupyterhub/jupyterhub_config.py

- name: copy swarm spawner script
  copy: src=swarmspawner.py dest=/srv/jupyterhub/swarmspawner.py

- name: copy adduser script
  copy: src=addusers.sh dest=/srv/jupyterhub/addusers.sh

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub/userlist

- name: copy custom login html
  copy: src=login.html dest=/srv/jupyterhub/login.html
