---
- fail: msg="jupyterhub_admin_user is not defined"
  when: jupyterhub_admin_user == ''

- include: jupyterhub.yml
- include: cull.yml
- include: stats.yml

- name: install docker compose
  template: src=docker-compose.yml dest=/root/docker-compose.yml

- name: stop docker containers
  command: docker-compose stop

- name: remove docker containers
  command: docker-compose rm -f

- name: pull docker images
  command: docker-compose pull

- name: build docker images
  command: docker-compose build

- name: run jupyterhub
  command: docker-compose up -d jupyterhub

- name: wait for jupyterhub to start
  command: docker logs root_jupyterhub_1
  register: jpy_status
  until: jpy_status.stderr.find("JupyterHub is now running") != -1
  retries: 5
  delay: 5

- name: get a jupyterhub api token
  command: docker exec root_jupyterhub_1 jupyterhub token -f /srv/jupyterhub_config/jupyterhub_config.py {{ jupyterhub_admin_user }}
  register: jpy_api_token

- name: start remaining services
  shell: JPY_API_TOKEN={{ jpy_api_token.stdout|lower }} docker-compose up -d --no-recreate
