---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  roles:
  - common
  tags:
  - common

- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - docker
  tags:
  - docker

- hosts:
  - jupyterhub_host
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - nfs_server
#  - duplicity

- hosts:
  - jupyterhub_nodes
  roles:
  - nfs_client

- hosts:
  - jupyterhub_host
  vars_files:
  - vars.yml
  roles:
  - consul_server

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - consul_client

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - singleuser
  tags:
  - singleuser

- hosts: 
  - jupyterhub_host
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - hub
  tags:
  - hub

- hosts:
  - proxy
  vars_files:
  - vars.yml
  roles:
  - proxy
  tags:
  - proxy

