FROM centos:centos7

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN yum -y update && \
    yum -y install vim libcurl-openssl libcurl-openssl-devel && \
    yum -y install mod_ssl

RUN cd /etc/httpd/conf && \
    echo 'UseCanonicalName On' >> httpd.conf && \
    echo 'LoadModule proxy_module modules/mod_proxy.so' >> httpd.conf && \
    echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> httpd.conf && \
    echo 'LoadModule ssl_module modules/mod_ssl.so' >> httpd.conf && \
    echo 'LoadModule proxy_wstunnel_module mod_proxy_wstunnel.so' >> httpd.conf && \
    echo 'Include /etc/httpd/conf/extra/httpd-vhosts.conf' >> httpd.conf

COPY httpd-vhosts.conf /etc/httpd/conf/extra/httpd-vhosts.conf
COPY 00-mpm.conf /etc/httpd/conf.modules.d/00-mpm.conf
COPY httpd-foreground /usr/local/bin/

EXPOSE 80 443

CMD ["/usr/local/bin/httpd-foreground"]
