FROM edwardjkim/httpd

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN cd $HTTPD_PREFIX/conf && \
    echo 'UseCanonicalName On' >> httpd.conf && \
    echo 'LoadModule proxy_module lib64/httpd/modules/mod_proxy.so' >> httpd.conf && \
    echo 'LoadModule proxy_http_module lib64/httpd/modules/mod_proxy_http.so' >> httpd.conf && \
    echo 'LoadModule ssl_module lib64/httpd/modules/mod_ssl.so' >> httpd.conf && \
    echo 'LoadModule proxy_wstunnel_module lib64/httpd/modules/mod_proxy_wstunnel.so' >> httpd.conf && \
    echo "Include $HTTPD_PREFIX/conf/extra/httpd-vhosts.conf" >> httpd.conf

COPY httpd-vhosts.conf "$HTTPD_PREFIX/conf/extra/httpd-vhosts.conf"
