FROM centos:centos7

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

ENV HTTPD_PREFIX /etc/httpd
ENV PATH $HTTPD_PREFIX/bin:$PATH
WORKDIR $HTTPD_PREFIX

RUN yum -y update && \
    yum -y install \
        vim \
        wget \
        bzip2 \
        gcc \
        pcre-devel \
        openssl-devel \
        make

ENV HTTPD_VERSION 2.4.23
ENV HTTPD_SHA1 5101be34ac4a509b245adb70a56690a84fcc4e7f
ENV HTTPD_BZ2_URL https://www.apache.org/dist/httpd/httpd-$HTTPD_VERSION.tar.bz2
ENV APR_VERSION 1.5.2
ENV APR_BZ2_URL http://mirror.cogentco.com/pub/apache//apr/apr-$APR_VERSION.tar.bz2
ENV APR_UTIL_VERSION 1.5.4
ENV APR_UTIL_BZ2_URL http://mirror.cogentco.com/pub/apache//apr/apr-util-$APR_UTIL_VERSION.tar.bz2

RUN set - x && \
    wget -O httpd.tar.bz2 "$HTTPD_BZ2_URL" && \
    echo "$HTTPD_SHA1 *httpd.tar.bz2" | sha1sum -c - && \
    wget -O httpd.tar.bz2.asc "$HTTPD_BZ2_URL.asc" && \
    export GNUPGHOME="$(mktemp -d)" && \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys A93D62ECC3C8EA12DB220EC934EA76E6791485A8 && \
    gpg --batch --verify httpd.tar.bz2.asc httpd.tar.bz2 && \
    rm -r "$GNUPGHOME" httpd.tar.bz2.asc && \
    mkdir -p src && \
    tar -xvf httpd.tar.bz2 -C "$HTTPD_PREFIX/src" && \
    rm httpd.tar.bz2

RUN cd $HTTPD_PREFIX/src && \
    wget -O apr.tar.bz2 "$APR_BZ2_URL" && \
    tar -xvjf apr.tar.bz2 && \
    rm apr.tar.bz2 && \
    mv "apr-$APR_VERSION" "httpd-$HTTPD_VERSION/srclib/apr" && \
    wget -O apr_util.tar.bz2 "$APR_UTIL_BZ2_URL" && \
    tar -xvjf apr_util.tar.bz2 && \
    rm apr_util.tar.bz2 && \
    mv "apr-util-$APR_UTIL_VERSION" "httpd-$HTTPD_VERSION/srclib/apr-util"

RUN cd $HTTPD_PREFIX/src/httpd-$HTTPD_VERSION && \
    ./configure --prefix="$HTTPD_PREFIX" --enable-mods-shared=reallyall && \
    make -j"$(nproc)" && \
    make install

RUN rm -r $HTTPD_PREFIX/src

RUN cd $HTTPD_PREFIX/conf && \
    echo 'UseCanonicalName On' >> httpd.conf && \
    echo 'LoadModule proxy_module modules/mod_proxy.so' >> httpd.conf && \
    echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> httpd.conf && \
    echo 'LoadModule ssl_module modules/mod_ssl.so' >> httpd.conf && \
    echo 'LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so' >> httpd.conf && \
    echo "Include $HTTPD_PREFIX/conf/extra/httpd-vhosts.conf" >> httpd.conf

COPY httpd-vhosts.conf $HTTPD_PREFIX/conf/extra/httpd-vhosts.conf
COPY httpd-foreground /usr/local/bin/

EXPOSE 80 443

CMD ["/usr/local/bin/httpd-foreground"]
