FROM jupyter/datascience-notebook

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    openssh-client

CMD ["start-singleuser.sh"]

USER $NB_USER

# Install Python 3 packages
RUN conda install --quiet --yes \
    'tensorflow=1.1*' \
    'keras=2.0*'

# Install Python 2 Tensorflow
RUN conda install --quiet --yes -n python2 \
    'tensorflow=1.1*' \
    'keras=2.0*'
