FROM jupyter/datascience-notebook

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    openssh-client

CMD ["start-singleuser.sh"]

USER $NB_USER

# Install Python 3 packages
RUN conda install --quiet --yes \
    'tensorflow=1.1*' \
    'keras=2.0*' \
    'joblib=0.11*'

# a bug in jupyterhub 0.8.0
# https://github.com/jupyterhub/wrapspawner/issues/11
RUN conda uninstall --quiet --yes jupyterhub
RUN conda install --quiet --yes \
    'jupyterhub=0.7*'
