swarm:
  image: swarm:1.2.8
  restart: always
  command: >
    manage 
    --tlsverify
    --tlscacert /root/.docker/ca.pem
    --tlscert /root/.docker/cert.pem
    --tlskey /root/.docker/key.pem
    --discovery-opt kv.cacertfile=/root/.docker/ca.pem
    --discovery-opt kv.certfile=/root/.docker/cert.pem
    --discovery-opt kv.keyfile=/root/.docker/key.pem
    "consul://{{ private_ip }}:8501/swarm"
  volumes:
    - /root/.docker:/root/.docker
  ports:
    - "{{ docker_server_port }}:2375"

jupyterhub:
  build: /srv/jupyterhub
  restart: always
  environment:
    HUB_IP: "{{ private_ip }}"
    DOCKER_TLS_CERT: /root/.docker/cert.pem
    DOCKER_TLS_KEY: /root/.docker/key.pem
    JPY_COOKIE_SECRET: "{{ cookie_secret }}"
    CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
  ports:
    - "{{ private_ip }}:8000:8000"
    - "{{ private_ip }}:8081:8081"
  volumes:
    - /srv/jupyterhub_users:/srv/jupyterhub_users
    - /root/.docker:/root/.docker
    - /export:/export
  links:
    - swarm

cull:
    build: /srv/cull
    restart: always
    command: --timeout=86400 --cull_every=3600 --url=http://jupyterhub:8081/hub
    environment:
      JPY_API_TOKEN:
    volumes:
      - /root/.docker:/root/.docker
    links:
      - jupyterhub

stats:
    build: /srv/stats
    restart: always
    command: --file=/srv/stats_db/activity.sqlite --hub=http://jupyterhub:8081
    environment:
      JPY_API_TOKEN:
    volumes:
      - /srv/stats_db:/srv/stats_db
    links:
      - jupyterhub
