FROM jupyter/jupyterhub:latest

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN apt-get update && \
    pip install --upgrade pip && \
    pip install docker-py && \
    pip install git+git://github.com/jupyter/dockerspawner.git && \
    pip install git+git://github.com/jupyter/oauthenticator.git

RUN mkdir /srv/jupyterhub_config
WORKDIR /srv/jupyterhub_config

ADD swarmspawner.py /srv/jupyterhub_config/swarmspawner.py
ADD jupyterhub_config.py /srv/jupyterhub_config/jupyterhub_config.py
ADD addusers.sh /srv/jupyterhub_config/addusers.sh
ADD userlist /srv/jupyterhub_config/userlist

ADD login.html /opt/conda/share/jupyter/hub/templates/login.html

EXPOSE 8080
EXPOSE 8001

# environment variable for swarm
ENV DOCKER_HOST https://swarm:2375

ENV OAUTH_CALLBACK_URL {{oauth_callback_url}}
ENV GITHUB_CLIENT_ID {{github_client_id}}
ENV GITHUB_CLIENT_SECRET {{github_client_secret}}

ENTRYPOINT ["jupyterhub", "-f", "/srv/jupyterhub_config/jupyterhub_config.py"]

RUN ["sh", "/srv/jupyterhub_config/addusers.sh"]
