FROM jupyterhub/jupyterhub:0.7.2

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN apt-get update && \
    pip install --upgrade pip && \
    pip install docker==2.3.0 && \
    pip install dockerspawner==0.7 && \
    pip install oauthenticator==0.5

RUN mkdir /srv/jupyterhub_config
WORKDIR /srv/jupyterhub_config

ADD swarmspawner.py /srv/jupyterhub_config/swarmspawner.py
ADD jupyterhub_config.py /srv/jupyterhub_config/jupyterhub_config.py
ADD addusers.sh /srv/jupyterhub_config/addusers.sh
ADD userlist /srv/jupyterhub_config/userlist

ADD login.html /opt/conda/share/jupyter/hub/templates/login.html

EXPOSE 8080
EXPOSE 8001

# environment variable for swarm
ENV DOCKER_HOST https://swarm:2375

ENV OAUTH_CALLBACK_URL {{oauth_callback_url}}
ENV OAUTH_CLIENT_ID {{oauth_client_id}}
ENV OAUTH_CLIENT_SECRET {{oauth_client_secret}}

ENTRYPOINT ["jupyterhub", "-f", "/srv/jupyterhub_config/jupyterhub_config.py"]

RUN ["sh", "/srv/jupyterhub_config/addusers.sh"]
