---
- name: create the singleuser directory
  file: path=/srv/singleuser state=directory

- name: copy the Dockerfile to the singleuser directory
  template: src=Dockerfile.singleuser.j2 dest=/srv/singleuser/Dockerfile

- name: pull lcdm/accy image
  shell: docker pull jupyter/datascience-notebook

- name: build singleuser image
  shell: docker build -t singleuser /srv/singleuser
