---
- name: install nfs pakcages
  yum: name=nfs-utils,libnfsidmap state=latest

- name: unmount home
  shell: umount /home || true

- name: mount home
  mount: name=/home src={{ hostvars['jupyterhub_host']['private_ip'] }}:/home fstype=nfs opts={{ nfsoptions }} state=mounted

- name: unmount group shared directory
  shell: umount /shared || true

- name: mount group shared directory
  mount: name=/shared src={{ hostvars['jupyterhub_host']['private_ip'] }}:/shared fstype=nfs opts={{ nfsoptions }} state=mounted
